In [1]:
import pandas as pd
from collections import Counter

df = pd.read_csv("transacoes_1.4.csv")

df.head(3)

,carrinho,produto,descricao,categoria
0,380962,4059805069114,CAMISETA SUPERNOVA M RAWSTE M,RUNNING
1,380962,4055017073826,MEIA LINER CUSHION 3S 3P WHITE/WHITE/BLACK 3538,TRAINING
2,380962,4058032608264,CAMISETA MC FREELIFT PRIME GRNNIT M,TRAINING

## Obtenção dos produtos mais vendidos que fazem sentido

In [2]:
itens_mais_comprados = Counter(df['produto'].to_list()).most_common()

itens_mais_comprados[:15]

[(4055342869637, 9239),
 (4062062914349, 7881),
 (4062062914318, 7430),
 (4055342869644, 7080),
 (4062062914332, 5493),
 (20000000000068, 4772),
 (20000000000070, 4772),
 (4062062914325, 4691),
 (4052549968248, 4674),
 (4064043251115, 3687),
 (4062062914301, 3497),
 (4062055329815, 3494),
 (4055017073819, 3299),
 (4062058558281, 3226),
 (4061616047564, 3077)]

In [3]:
def produto(id):
    return df.loc[df['produto'] == id][:1]["descricao"].iloc[0]

In [4]:
lista_mais_vendidos = [(4055342869637, 9239),
 (4062062914349, 7881),
 (4062062914318, 7430),
 (4055342869644, 7080),
 (4062062914332, 5493),
 (20000000000068, 4772),
 (20000000000070, 4772),
 (4062062914325, 4691),
 (4052549968248, 4674),
 (4064043251115, 3687),
 (4062062914301, 3497),
 (4062055329815, 3494),
 (4055017073819, 3299),
 (4062058558281, 3226),
 (4061616047564, 3077)]
  
for i in lista_mais_vendidos:
    print(produto(i[0]))
    print(i[0])
    print("-------")

LETRA AVULSA MULTCO NT
4055342869637
-------
TENIS SUPERSTAR SLIP ON W CBLACK 35
4062062914349
-------
TENIS SUPERSTAR SLIP ON W CBLACK 36
4062062914318
-------
NR INT CLUB MULTCO NT
4055342869644
-------
TENIS SUPERSTAR SLIP ON W CBLACK 37
4062062914332
-------
KIT  FRESCOBOL -2
20000000000068
-------
BARALHO PERSONALIZADO PAPEL CARTAO 300 GR -2
20000000000070
-------
TENIS SUPERSTAR SLIP ON W CBLACK 34
4062062914325
-------
CARTEIRA GLAM preto NT
4052549968248
-------
MEIA LINER TREFOIL WHITE/WHITE/BLACK M
4064043251115
-------
TENIS SUPERSTAR SLIP ON W CBLACK 38
4062062914301
-------
BAG PARKHOOD CBB BLACK/BLACK/SOLRED NT
4062055329815
-------
MEIA LINER CUSHION 3S 3P WHITE/WHITE/BLACK 3942
4055017073819
-------
MEIA LINER TREFOIL WHITE/BLACK/MGREYH 3942
4062058558281
-------
BONE BASEBALL CLASS TRF BLACK/WHITE OSFM
4061616047564
-------

In [5]:
print(produto(4062062914349))
print(produto(4052549968248))
print(produto(4064043251115))

TENIS SUPERSTAR SLIP ON W CBLACK 35
CARTEIRA GLAM preto NT
MEIA LINER TREFOIL WHITE/WHITE/BLACK M

## Obtenção de sample de carrinhos reais para teste de qualidade

In [6]:
df_gb = df.groupby(["carrinho"])

In [7]:
df_gb.head(3)

,carrinho,produto,descricao,categoria
0,380962,4059805069114,CAMISETA SUPERNOVA M RAWSTE M,RUNNING
1,380962,4055017073826,MEIA LINER CUSHION 3S 3P WHITE/WHITE/BLACK 3538,TRAINING
2,380962,4058032608264,CAMISETA MC FREELIFT PRIME GRNNIT M,TRAINING
4,329797,4057288560432,BERMUDA KNIT MGREYH/TRAGRE XL,ATHLETICS
5,329797,4058031626313,BERMUDA COLOURBLOCK CONAVY/CONAVY S,ATHLETICS
...,...,...,...,...
1959979,3920069,4064045375116,SHORTS LOGO LINEAR CHELSEA LEGINK/WHITE L,CORE SPORTS INSPIRED
1960063,4564066,4064044807366,CAMISETA TREFOIL BLACK M,ORIGINALS
1960064,4564066,4064055012674,CAMISETA TREFOIL WHITE/BLACK XL,ORIGINALS
1960097,4596701,4065419801613,NaN,NaN
1960098,4596701,4064055096339,"SHORTS OWN THE RUN VICBLU M 7""",RUNNING

In [8]:
df.shape

(1960186, 4)

In [21]:
df_gb = df_gb.count().sort_values('produto', ascending=False)

#### Números abaixo foram pegos para cumprir o papel de ter variedade na quantidade de produtos no carrinho,   aqueles que possuem por exemplo "9001", era por que o 9000 tinha produto com descrição nula

In [40]:
df.isnull().sum().sort_values(ascending = False)

descricao    122007
categoria    122007
carrinho          0
produto           0
dtype: int64

In [102]:
print(df_gb.iloc[4500].name, df_gb.iloc[4500].produto)
print(df_gb.iloc[9001].name, df_gb.iloc[9001].produto)
print(df_gb.iloc[27000].name, df_gb.iloc[27000].produto)
print(df_gb.iloc[45000].name, df_gb.iloc[45000].produto)
print(df_gb.iloc[90000].name, df_gb.iloc[90000].produto)
print(df_gb.iloc[135000].name, df_gb.iloc[135000].produto)
print(df_gb.iloc[180000].name, df_gb.iloc[180000].produto)
print(df_gb.iloc[270001].name, df_gb.iloc[270001].produto)
print(df_gb.iloc[360000].name, df_gb.iloc[360000].produto)
print(df_gb.iloc[450000].name, df_gb.iloc[450000].produto)
lista_carrinhos = []
lista_carrinhos.append([df_gb.iloc[4500].name,df_gb.iloc[9001].name,df_gb.iloc[27000].name,df_gb.iloc[45000].name,
                       df_gb.iloc[90000].name,df_gb.iloc[135000].name,df_gb.iloc[180000].name,df_gb.iloc[270001].name,
                       df_gb.iloc[360000].name,df_gb.iloc[450000].name])
print(lista_carrinhos[0])

1938144 10
3491421 8
3255963 6
589266 5
3356795 4
3575578 3
569397 3
2793765 2
4391264 2
2093812 2
[1938144, 3491421, 3255963, 589266, 3356795, 3575578, 569397, 2793765, 4391264, 2093812]

## Gerarando dataframe com os testes internos

In [103]:
df_testes_carrinho = pd.DataFrame(lista_carrinhos[0] ,columns=['carrinho'])
df_testes_carrinho

   carrinho
0   1938144
1   3491421
2   3255963
3    589266
4   3356795
5   3575578
6    569397
7   2793765
8   4391264
9   2093812

#### garantindo que não há descrições nulas

In [95]:
df[df["produto"]==4064044992338]

,carrinho,produto,descricao,categoria
30521,4433296,4064044992338,NaN,NaN
36216,3419902,4064044992338,SHORTS ESSENTIALS 3 LISTRAS LEGINK/WHITE M,CORE SPORTS INSPIRED
37734,4607237,4064044992338,SHORTS ESSENTIALS 3 LISTRAS LEGINK/WHITE M,CORE SPORTS INSPIRED
93403,3240682,4064044992338,SHORTS ESSENTIALS 3 LISTRAS LEGINK/WHITE M,CORE SPORTS INSPIRED
96128,4470379,4064044992338,NaN,NaN
...,...,...,...,...
1943298,3707279,4064044992338,SHORTS ESSENTIALS 3 LISTRAS LEGINK/WHITE M,CORE SPORTS INSPIRED
1944073,4589971,4064044992338,NaN,NaN
1952011,4297117,4064044992338,SHORTS ESSENTIALS 3 LISTRAS LEGINK/WHITE M,CORE SPORTS INSPIRED
1956103,4140240,4064044992338,SHORTS ESSENTIALS 3 LISTRAS LEGINK/WHITE M,CORE SPORTS INSPIRED
1956129,4645698,4064044992338,NaN,NaN

In [98]:
df.isnull().sum().sort_values(ascending = False)

descricao    122007
categoria    122007
carrinho          0
produto           0
dtype: int64

In [104]:
def produtos_por_carrinho(carrinho):
    produto = df[df["carrinho"]==carrinho].produto.to_list()
    desc = df[df["carrinho"]==carrinho].descricao.to_list()
    return [produto, desc]
    
produtos = []
descs = []
for i in lista_carrinhos[0]:
    x = produtos_por_carrinho(i)
    produtos.append(x[0])
    descs.append(x[1])
    
for a in descs:
    print("\n\n----------------------")
    print(a)

----------------------
['SHORT CB SH SL LEGINK/GRETWO/SHOCYA M', 'TOP ASK SPT BRA F HIREOR/PRINT L', 'CHUTEIRA PREDATOR 18 4 IN JR CBLACK/FTWWHT/RED 32', 'alphabounce em m    CONAVY/FTWWHT/GREFIV CONAVY/FTWWHT/GREFIV 40', 'CAMISA INTER I ACTRED L', 'CALCA ASK SPT 34T F HIREOR/PRINT L', 'TENIS PROPHERE W TRAMAR/NOBMAR/SOLRED 39', 'MEIA ULT AN HC BLACK/WHITE 3739', 'CAMISETA AI BLACK M', 'CALCA ASK SPT 34T F HIREOR/PRINT M']



----------------------
['SHORTS D2M SEASONAL BLACK/WHITE L', 'BERMUDA 3 STRIPES MGREYH L', 'BERMUDA 3 STRIPES MGREYH XL', 'CAMISETA FUTURE ICON AIDDAS WHITE XL', 'SHORTS FUTURE ICON 3 BAR BLACK XL', 'SHORTS FUTURE ICON 3 BAR BLACK L', 'CHAPEU BUCKET ORIGINALS BLACK OSFM', 'CAMISETA ESTAMPADA LINEAR WHITE L']



----------------------
['MEIA FOLD CUFF CREW WHITE S', 'MEIA MID CUT GLITTER WHITE/SILVMT S', 'CALCA TIGHT ORIGINALS BLACK M', 'CALCA LEGGINGS ORIGINALS BLACK M', 'BLUSA CROPPED HOODIE MULTCO M', 'SHORTS ORIGINALS MULTCO M']



----------------------
['CAMISETA CAMO TREF TEE WHITE L', 'CAMISETA TREFOIL BLACK L', 'MEIA THIN CR SOCK GR CLBLUE/WHITE 3538', 'CAMISETA HAND DRAWN T2 WHITE M', 'TENIS SUPERSTAR FOUNDATION WHITE/CBLACK/WHITE 43']



----------------------
['MEIA CANO BAIXO 3 PARES WHITE/WHITE/WHITE M', 'MEIA CANO MEDIO 3 PARES BLACK/BLACK/BLACK M', 'MEIA ANKLE MID WHITE/WHITE/BLACK M', 'MEIA CANO BAIXO 3 PARES WHITE/WHITE/WHITE M']



----------------------
['BOLSA FESTIVAL MONOGRAM BLACK/WHITE NT', 'BERMUDA SPRT WHITE/MULTCO XL', 'MEIA CREW SOLID WHITE/BLACK/WHITE/BLACK M']



----------------------
['TENIS SEELEY CONAVY/FTWWHT/CBLACK 41', 'TENIS SUPERSTAR FOUNDATION FTWWHT/FTWWHT/FTWWHT 41', 'TENIS ADI EASE CBLACK/FTWWHT/CBLACK 41']



----------------------
['MEIA LINER TREFOIL WHITE/WHITE/BLACK S', 'TENIS SUPERSTAR SLIP ON W CBLACK 35']



----------------------
['SHORTS FARM BLACK S', 'TOP SUPORTE LEVE HYPERGLAM Q2 BLACK MAC']



----------------------
['CALCA TP CARDBO XL', 'BONE CORDUROY MESA OSFM']

In [105]:
df_testes_carrinho['id_produtos'] = produtos
df_testes_carrinho['desc_produtos'] = descs
df_testes_carrinho

,carrinho,id_produtos,desc_produtos
0,1938144,"[4060515261064, 4059807341744, 4059811961976, ...","[SHORT CB SH SL LEGINK/GRETWO/SHOCYA M, TOP AS..."
1,3491421,"[4064054469653, 4060507958217, 4060507958132, ...","[SHORTS D2M SEASONAL BLACK/WHITE L, BERMUDA 3 ..."
2,3255963,"[4062065488564, 4062065434844, 4062055082451, ...","[MEIA FOLD CUFF CREW WHITE S, MEIA MID CUT GLI..."
3,589266,"[4060507801971, 4059322005596, 4059807879308, ...","[CAMISETA CAMO TREF TEE WHITE L, CAMISETA TREF..."
4,3356795,"[4061626844528, 4061626835946, 4062054919758, ...","[MEIA CANO BAIXO 3 PARES WHITE/WHITE/WHITE M, ..."
5,3575578,"[4064057794004, 4064048708973, 4064043251122]","[BOLSA FESTIVAL MONOGRAM BLACK/WHITE NT, BERMU..."
6,569397,"[4055344854990, 4056563522868, 4054075521591]","[TENIS SEELEY CONAVY/FTWWHT/CBLACK 41, TENIS S..."
7,2793765,"[4064043251092, 4062062914349]","[MEIA LINER TREFOIL WHITE/WHITE/BLACK S, TENIS..."
8,4391264,"[4065423688828, 4065432236553]","[SHORTS FARM BLACK S, TOP SUPORTE LEVE HYPERGL..."
9,2093812,"[4062056078330, 4062059489607]","[CALCA TP CARDBO XL, BONE CORDUROY MESA OSFM]"

In [107]:
df_testes_carrinho.to_csv("testes_carrinho.csv", index=False)

In [2]:
df.sample(15)

,carrinho,produto,descricao,categoria
484838,3724277,4064044181299,CAMISETA D2M PLAIN WHITE/BLACK L,CORE SPORTS
1645861,1204076,4060513595796,CAMISETA M ID STDM 3S T MYSINK L,ATHLETICS
1648972,2227835,4062058600362,AGASALHO W TS TEAMSPORTS SKYTIN/LEGINK S,ATHLETICS
731003,2133421,4055012809949,MEIA CREW SOLID BLACK/WHITE 3942,ORIGINALS
671499,2854485,4061619010671,BOLSA FEST TREFOIL BLACK NT,ORIGINALS
460736,332610,4056559629335,CAMISETA BOYFRIEND TREFOIL BLACK S,ORIGINALS
1904541,3813442,4064055069524,"SHORTS OWN THE RUN BLACK/SONAQU XL7""",RUNNING
333157,4328503,4065424058682,CAMISETA OWN THE RUN ORARUS S,RUNNING
1216318,3972001,4064045241381,SHORTS CHELSEA LOGO PEQUENO BLACK/WHITE M,CORE SPORTS INSPIRED
889628,4375173,4064045968370,CAMISETA 3 STRIPES WHITE M,ORIGINALS
695636,1508939,4059812356139,CAMISETA ALIVE W CLEMIN/WHITE S,RUNNING
1202305,1506806,4059812365278,JAQUETA ZNE W SHORED S,RUNNING
1830014,2242458,4060519284267,CALCA SST dmc TP BLACK/RED XL,ORIGINALS
110947,3039304,4064044780720,CALCA FIREBIRD TP PB BLACK L,ORIGINALS
983971,4590008,4060512348676,CAMISETA LOGO ADIDAS BLACK/WHITE M,SPORTSWEAR

### Gerando base de dados exemplar para apresentação no streamlit

In [24]:
pesquisa = pd.read_csv("dados_pesquisa1.csv", sep=',')
pesquisa = pesquisa.iloc[:10]
pesquisa.head(3)

,carrinho,id_produtos,desc_produtos,primeira_rec,segunda_rec,terceira_rec,P11,P21,P31,P12,...,P33,P14,P24,P34,P15,P25,P35,P16,P26,P36
0,1938144,"[4060515261064, 4059807341744, 4059811961976, ...","['SHORT CB SH SL LEGINK/GRETWO/SHOCYA M', 'TOP...",MEIA CANO MEDIO 3 PARES BLACK/BLACK/BLACK M,LETRA AVULSA MULTCO NT,NR INT CLUB MULTCO NT,1,1,2,1,...,1,1,1,2,1,0,1,0,0,0
1,3491421,"[4064054469653, 4060507958217, 4060507958132, ...","['SHORTS D2M SEASONAL BLACK/WHITE L', 'BERMUDA...",BERMUDA 3 STRIPES BLACK L,KIT FRESCOBOL -2,BARALHO PERSONALIZADO PAPEL CARTAO 300 GR -2,0,0,2,1,...,2,1,0,2,0,0,1,2,1,1
2,3255963,"[4062065488564, 4062065434844, 4062055082451, ...","['MEIA FOLD CUFF CREW WHITE S', 'MEIA MID CUT ...",CALCA ORIGINALS MULTCO M,MEIA TRICOLOR THIN WHITE M,REGATA CORSET WHITE S,2,2,2,0,...,2,1,2,2,1,2,1,1,1,1

In [18]:
pesquisa.shape

(10, 24)

In [29]:
prods = pd.DataFrame(columns=['ID', "DESC"])

eval(pesquisa.iloc[1,1])

for index, row in pesquisa.iterrows():
    for i in range(len(eval(row['desc_produtos']))):
        prods.loc[-1] = [eval(row['id_produtos'])[i], eval(row['desc_produtos'])[i]]
        prods.index = prods.index + 1
        prods = prods.sort_index()
prods.shape

(45, 2)

In [28]:
prods.duplicated(subset='ID').sum()

1

In [30]:
prods = prods.drop_duplicates(subset='ID')

In [31]:
prods.shape

(44, 2)

In [32]:
prods.to_csv("produtos_short.csv", index=False)